// AUTO-GENERATED manifest of real photography (alt + intrinsic size).
// Source: thechigwellmarquees.com WP media library. Edit curated picks below by hand.

export type Media = { src: string; alt: string; width: number; height: number };

const M: Record<string, { a: string; w: number; h: number }> = {
  "beautiful-essex-wedding-venue.jpg": { a: "Wedding Venues in Essex | Chigwell | Essex", w: 700, h: 450 },
  "asian-wedding-mandap-hire-1.jpg": { a: "Asian Wedding Mandap Hire | Chigwell | Essex", w: 700, h: 450 },
  "marquee-hire-chigwell.jpg": { a: "Party Venue Essex | Chigwell | Essex", w: 700, h: 450 },
  "party-venue-chigwell.jpg": { a: "Essex Party Venue | Chigwell | Essex", w: 700, h: 450 },
  "christening-venues-near-me-essex-chigwell-marquees.jpg": { a: "Christening Venue - Essex - Greater London - Chigwell Marquees", w: 550, h: 550 },
  "christmas-party-venue-essex-chigwell-marquees.jpg": { a: "Christmas Party Venue - Essex - Greater London - Chigwell Marquees", w: 550, h: 550 },
  "corporate-event-venue-hire-essex-chigwell-marquees.jpg": { a: "Corporate Event Venue Hire - Essex - Greater London - Chigwell Marquees", w: 550, h: 550 },
  "large-corporate-venue-hire-essex-chigwell-marquees.jpg": { a: "Large Corporate Venue Hire - Essex - Greater London - Chigwell Marquees", w: 550, h: 550 },
  "asian-weddings-essex-the-chigwell-marquees.jpg": { a: "Asian Weddings - Essex", w: 720, h: 420 },
  "civil-ceremony-venue-in-essex-civil-ceremony-marquee-hire-essex-the-chigwell-marquees.jpg": { a: "Civil Ceremony Venue In Essex - Civil Ceremony Marquee Hire - Essex", w: 550, h: 550 },
  "birthday-party-venue-in-essex-childrens-party-venues-essex-the-chigwell-marquees.jpg": { a: "Birthday Party Venue In Essex - Childrens party Venues - Essex", w: 550, h: 550 },
  "birthday-party-venue-in-essex-childrens-birthday-venues-essex-the-chigwell-marquees.jpg": { a: "Birthday Party Venue In Essex - Children's Birthday Venues - Essex", w: 550, h: 550 },
  "party-venue-in-essex-marquee-hire-essex-essex-the-chigwell-marquees.jpg": { a: "Party Venue In Essex - Marquee Hire Essex - Essex", w: 550, h: 550 },
  "party-venue-in-essex-events-marquee-for-hire-essex-the-chigwell-marquees.jpg": { a: "Party Venue In Essex - Events Marquee For Hire - Essex", w: 1160, h: 550 },
  "large-party-venue-marquee-venues-near-me-essex-the-chigwell-marquees.jpg": { a: "Large Party Venue - Marquee Venues Near Me - Essex", w: 1160, h: 550 },
  "engagement-party-venue-engagement-marquee-hire-essex-the-chigwell-marquees.jpg": { a: "Engagement Party Venue - Engagement Marquee Hire - Essex", w: 1160, h: 550 },
  "bengali-weddings-bengali-marquee-wedding-venues-essex-the-chigwell-marquees.jpg": { a: "Bengali Weddings - Bengali Marquee Wedding Venues - Essex", w: 550, h: 550 },
  "asian-weddings-asian-marquee-wedding-venues-essex-the-chigwell-marquees.jpg": { a: "Asian Weddings - Asian Marquee Wedding Venues - Essex", w: 550, h: 550 },
  "birthday-party-venue-party-marquee-essex-the-chigwell-marquees.jpg": { a: "Birthday Party Venue - Party Marquee - Essex", w: 550, h: 550 },
  "small-civil-ceremony-venue-luxury-marquee-event-hire-essex-the-chigwell-marquees.jpg": { a: "Small Civil Ceremony Venue - Luxury Marquee Event Hire - Essex", w: 900, h: 525 },
  "civil-ceremony-venue-essex-marquee-event-hire-essex-the-chigwell-marquees.jpg": { a: "Civil Ceremony Venue Essex - Marquee Event Hire - Essex", w: 1160, h: 550 },
  "civil-ceremony-venue-near-me-marquee-event-hire-essex-the-chigwell-marquees.jpg": { a: "Civil Ceremony Venue Near Me - Marquee Event Hire - Essex", w: 550, h: 550 },
  "civil-ceremony-marquee-hire-marquee-event-hire-essex-the-chigwell-marquees.jpg": { a: "Civil Ceremony Marquee Hire - Marquee Event Hire - Essex", w: 550, h: 550 },
  "civil-ceremony-venue-hire-marquee-event-hire-essex-the-chigwell-marquees.jpg": { a: "Civil Ceremony Venue Hire - Marquee Event Hire - Essex", w: 550, h: 550 },
  "engagement-venue-hire-luxury-marquee-hire-essex-the-chigwell-marquees.jpg": { a: "Engagement Venue hire - Luxury Marquee Hire - Essex", w: 900, h: 525 },
  "engagement-party-venue-marquee-hire-package-essex-the-chigwell-marquees.jpg": { a: "Engagement Party Venue - Marquee Hire Package - Essex", w: 1160, h: 550 },
  "indian-weddings-asian-weddings-essex-the-chigwell-marquees.jpg": { a: "Indian Weddings - Asian Weddings - Essex", w: 900, h: 525 },
  "bengali-weddings-wedding-venues-essex-the-chigwell-marquees.jpg": { a: "Bengali Weddings - Wedding Venues - Essex", w: 550, h: 550 },
  "asian-weddings-wedding-venues-essex-the-chigwell-marquees.jpg": { a: "Asian Weddings - Wedding Venues - Essex", w: 550, h: 550 },
  "wedding-venue-hire-luxury-wedding-marquees-essex-the-chigwell-marquees.jpg": { a: "Wedding Venue Hire - Luxury Wedding Marquees - Essex", w: 550, h: 550 },
  "asian-wedding-venue-luxury-wedding-marque-essex-the-chigwell-marquees.jpg": { a: "asian-wedding-venue-luxury-wedding-marque-essex-the-chigwell-marquees", w: 550, h: 550 },
  "wedding-venue-hire-marquee-wedding-venues-essex-the-chigwell-marquees.jpg": { a: "Wedding Venue Hire - Marquee Wedding Venues - Essex", w: 550, h: 550 },
  "asian-wedding-venue-marquee-wedding-venues-essex-the-chigwell-marquees.jpg": { a: "Asian Wedding Venue - Marquee Wedding Venues - Essex", w: 1160, h: 550 },
  "bengali-weddings-pakistani-wedding-essex-the-chigwell-marquees.jpg": { a: "Bengali Weddings - Pakistani Wedding - Essex", w: 550, h: 550 },
  "asian-weddings-indian-weddings-essex-the-chigwell-marquees.jpg": { a: "Asian Weddings - Indian Weddings - Essex", w: 550, h: 550 },
  "bengali-weddings-asian-weddings-essex-the-chigwell-marquees.jpg": { a: "bengali-weddings-asian-weddings-essex-the-chigwell-marquees", w: 1160, h: 550 },
  "asian-weddings-indian-wedding-essex-the-chigwell-marquees.jpg": { a: "Asian Weddings - Indian Weddings - Essex", w: 1160, h: 550 },
  "asian-weddings-bengali-weddings-essex-the-chigwell-marquees.jpg": { a: "Asian Weddings - Bengali Weddings - Essex", w: 1160, h: 550 },
  "party-venues-hire-birthday-events-venue-essex-the-chigwell-marquees.jpg": { a: "party-venues-hire-birthday-events-venue-essex-the-chigwell-marquees", w: 1160, h: 550 },
  "party-venues-essex-event-space-essex-the-chigwell-marquees.jpg": { a: "Party Venues Essex - Event Space - Essex", w: 1160, h: 550 },
  "party-venue-hire-birthday-party-venue-essex-the-chigwell-marquees.jpg": { a: "Party Venue Hire - Birthday Party Venue - Essex", w: 550, h: 550 },
  "party-venues-essex-private-party-venue-essex-the-chigwell-marquees.jpg": { a: "Party Venues Essex - Private Party Venue - Essex", w: 550, h: 550 },
  "party-venues-essex-party-venues-hire-essex-the-chigwell-marquees.jpg": { a: "Party Venues Essex - Party Venues Hire - Essex", w: 550, h: 550 },
  "party-venues-hire-party-venues-essex-essex-the-chigwell-marquees.jpg": { a: "Party Venues Hire - Party Venues Essex - Essex", w: 550, h: 550 },
  "civil-ceremoney-venue-hire-essex-the-chigwell-marquees.jpg": { a: "Civil Ceremony Venue Hire - Essex", w: 550, h: 550 },
  "civil-ceremoney-venue-to-rent-essex-the-chigwell-marquees.jpg": { a: "Civil Ceremony Venue To Rent - Essex", w: 550, h: 550 },
  "civil-ceremoney-venue-essex-the-chigwell-marquees.jpg": { a: "Civil Ceremony Venue - Essex", w: 1800, h: 800 },
  "engagement-parties-in-essex-the-chigwell-marquees.jpg": { a: "Engagement Parties In Essex - The Chigwell Marquee", w: 700, h: 450 },
  "engagement-venues-to-hire-essex-the-chigwell-marquee.jpg": { a: "Engagement Venues To Hire - Essex - The Chigwell Marquee", w: 700, h: 450 },
  "birthday-party-venue-party-venue-near-me-essex-the-chigwel-marquees.jpg": { a: "Birthday Party Venue - Party Venue Near Me - Essex", w: 1800, h: 800 },
  "festival-venue-hire-essex-chigwell-marquees.jpg": { a: "Festival Venue Hire - Essex - Chigwell Marquees", w: 1800, h: 680 },
  "corporate-venue-hire-essex-chigwell-marquees.jpg": { a: "Corporate Venue Hire - Essex - Chigwell Marquees", w: 1800, h: 680 },
  "wedding-venue-hire-asian-wedding-venue-essex-the-chigwell-marquees.jpg": { a: "Best Small Wedding Venues In Essex - Chigwell Marquees", w: 1800, h: 800 },
  "asian-wedding-venue-wedding-venue-hire-essex-the-chigwell-marquees.jpg": { a: "Asian Wedding Venue - Wedding Venue Hire - Essex", w: 720, h: 720 },
  "civil-ceremonies-essex-chigwell-marquees.jpg": { a: "Civil Ceremony Venue, Essex & London - Chigwell Marquees", w: 720, h: 420 },
  "wedding-venue-essex-chigwell-marquees.jpg": { a: "Wedding Venue, Essex & London - Chigwell Marquees", w: 720, h: 420 },
  "party-venue-essex-chigwell-marquees.jpg": { a: "Party Venue, Essex & London - Chigwell Marquees", w: 720, h: 420 },
  "birthday-party-venue-essex-chigwell-marquees.jpg": { a: "Birthday Party Venue, Essex & London - Chigwell Marquees", w: 720, h: 420 },
  "wedding-venue-chigwell-essex-1.jpg": { a: "Wedding Venues Essex - Chigwell Marquees - Essex", w: 1200, h: 360 },
  "chigwell-form-capture.jpg": { a: "chigwell-form-capture", w: 160, h: 30 },
  "xmas-bookings-2019.jpg": { a: "xmas-bookings-2019", w: 900, h: 250 },
  "the-chigwell-marquees-open-day.jpg": { a: "the-chigwell-marquees-open-day", w: 900, h: 250 },
  "essex-party-marquees.jpg": { a: "Party Venue Essex | Chigwell | Essex", w: 1120, h: 350 },
  "party-venues-near-me.jpg": { a: "Party Venues Near Me | Chigwell | Essex", w: 900, h: 450 },
  "engagement-parties-in-essex.jpg": { a: "Engagement Parties in Essex | Chigwell | Essex", w: 700, h: 450 },
  "engagement-party-venues.jpg": { a: "Engagement Party Venues | Chigwell | Essex", w: 700, h: 450 },
  "asian-wedding-mandap-hire.jpg": { a: "Asian Wedding Mandap Hire | Chigwell | Essex", w: 700, h: 450 },
  "party-venues-near-me-Essex.jpg": { a: "Party Venues Near Me | Essex | London", w: 1200, h: 360 },
  "asian-wedding-venue-near-me-essex-london.jpg": { a: "Asian Wedding Venue Near Me | Essex | London", w: 1200, h: 360 },
  "party-venue-essex.jpg": { a: "Birthday Party Venue | Marquee Hire | Chigwell | Essex", w: 520, h: 300 },
  "wedding-venue-essex-1.jpg": { a: "Wedding Venue Hire | Mega Marquee | Chigwell | Essex", w: 520, h: 300 },
  "civil-ceremonies-essex.jpg": { a: "civil-ceremonies-essex", w: 1200, h: 360 },
  "wedding-venue-essex.jpg": { a: "Wedding Venues Essex | Chigwell Marquees | Essex", w: 1200, h: 360 },
  "parties-chigwell-marquees.png": { a: "parties-chigwell-marquees", w: 360, h: 210 },
  "civil-ceremonies-chigwell-marquees.png": { a: "civil-ceremonies-chigwell-marquees", w: 360, h: 210 },
  "chigwell-marquees-about-us-1.png": { a: "chigwell-marquees-about-us", w: 1120, h: 350 },
  "chigwell-marquees-wedding.jpg": { a: "chigwell-marquees-wedding", w: 360, h: 210 },
  "chigwell-marquees-party.png": { a: "chigwell-marquees-party", w: 360, h: 210 },
  "chigwell-marquees-corporate-events.png": { a: "chigwell-marquees-corporate-events", w: 360, h: 210 },
  "chigwell-marquees-wedding.png": { a: "chigwell-marquees-wedding", w: 360, h: 210 },
  "chigwell-marquees-civil-ceremonies-02.jpg": { a: "chigwell-marquees-civil-ceremonies-02", w: 700, h: 450 },
  "chigwell-marquees-civil-ceremonies-01.jpg": { a: "chigwell-marquees-civil-ceremonies-01", w: 700, h: 450 },
  "chigwell-marquees-wedding-events-06.jpg": { a: "chigwell-marquees-wedding-events-06", w: 700, h: 450 },
  "chigwell-marquees-wedding-events-05.jpg": { a: "chigwell-marquees-wedding-events-05", w: 700, h: 450 },
  "chigwell-marquees-wedding-events-04.jpg": { a: "chigwell-marquees-wedding-events-04", w: 700, h: 450 },
  "chigwell-marquees-wedding-events-03.jpg": { a: "chigwell-marquees-wedding-events-03", w: 700, h: 450 },
  "chigwell-marquees-wedding-events-02.jpg": { a: "chigwell-marquees-wedding-events-02", w: 700, h: 450 },
  "chigwell-marquees-wedding-events-01.jpg": { a: "chigwell-marquees-wedding-events-01", w: 700, h: 450 },
  "chigwell-marquees-themed-events-05.jpg": { a: "chigwell-marquees-themed-events-05", w: 700, h: 450 },
  "chigwell-marquees-themed-events-04.jpg": { a: "chigwell-marquees-themed-events-04", w: 700, h: 450 },
  "chigwell-marquees-themed-events-03.jpg": { a: "chigwell-marquees-themed-events-03", w: 700, h: 450 },
  "chigwell-marquees-themed-events-02.jpg": { a: "chigwell-marquees-themed-events-02", w: 700, h: 450 },
  "chigwell-marquees-themed-events-01.jpg": { a: "chigwell-marquees-themed-events-01", w: 700, h: 450 },
  "chigwell-marquees-corporate-events-05.jpg": { a: "chigwell-marquees-corporate-events-05", w: 700, h: 450 },
  "chigwell-marquees-corporate-events-04.jpg": { a: "chigwell-marquees-corporate-events-04", w: 700, h: 450 },
  "chigwell-marquees-corporate-events-03.jpg": { a: "chigwell-marquees-corporate-events-03", w: 700, h: 450 },
  "chigwell-marquees-corporate-events-02.jpg": { a: "chigwell-marquees-corporate-events-02", w: 700, h: 450 },
  "chigwell-marquees-corporate-events-01.jpg": { a: "chigwell-marquees-corporate-events-01", w: 700, h: 450 },
  "chigwell-marquees-large-marquee.jpg": { a: "chigwell-marquees-large-marquee", w: 1800, h: 1125 },
  "chigwell-marquees-mandaps.jpg": { a: "chigwell-marquees-mandaps", w: 1800, h: 1125 },
  "chigwell-holding-page.png": { a: "chigwell-holding-page", w: 620, h: 459 },
  "garden-wedding-essex-london-chigwell-marquees.jpg": { a: "Garden wedding setting at The Chigwell Marquees, Essex", w: 520, h: 300 },
  "mega-marquee-wedding-venue-essex-london-chigwell-marquees.jpg": { a: "The Mega Marquee wedding venue, Essex & London", w: 520, h: 300 },
  "mini-marquee-party-venue-essex-london-chigwell-marquees.jpg": { a: "The Mini Marquee party venue, Essex & London", w: 520, h: 300 },
  "party-venue-chigwell-essex.jpg": { a: "Party venue interior at The Chigwell Marquees, Chigwell Essex", w: 1800, h: 1125 },
};

/** Resolve a media file (by filename) to a typed {src,alt,width,height}. */
export function img(file: string, altOverride?: string): Media {
  const m = M[file];
  if (!m) throw new Error("Unknown media: " + file);
  return { src: "/media/" + file, alt: altOverride ?? m.a, width: m.w, height: m.h };
}

/** Every usable photograph (>= 520px wide), for the gallery. */
export const GALLERY_FILES: string[] = ["chigwell-marquees-large-marquee.jpg","chigwell-marquees-mandaps.jpg","party-venue-chigwell-essex.jpg","civil-ceremoney-venue-essex-the-chigwell-marquees.jpg","birthday-party-venue-party-venue-near-me-essex-the-chigwel-marquees.jpg","wedding-venue-hire-asian-wedding-venue-essex-the-chigwell-marquees.jpg","festival-venue-hire-essex-chigwell-marquees.jpg","corporate-venue-hire-essex-chigwell-marquees.jpg","party-venue-in-essex-events-marquee-for-hire-essex-the-chigwell-marquees.jpg","large-party-venue-marquee-venues-near-me-essex-the-chigwell-marquees.jpg","engagement-party-venue-engagement-marquee-hire-essex-the-chigwell-marquees.jpg","civil-ceremony-venue-essex-marquee-event-hire-essex-the-chigwell-marquees.jpg","engagement-party-venue-marquee-hire-package-essex-the-chigwell-marquees.jpg","asian-wedding-venue-marquee-wedding-venues-essex-the-chigwell-marquees.jpg","bengali-weddings-asian-weddings-essex-the-chigwell-marquees.jpg","asian-weddings-indian-wedding-essex-the-chigwell-marquees.jpg","asian-weddings-bengali-weddings-essex-the-chigwell-marquees.jpg","party-venues-hire-birthday-events-venue-essex-the-chigwell-marquees.jpg","party-venues-essex-event-space-essex-the-chigwell-marquees.jpg","asian-wedding-venue-wedding-venue-hire-essex-the-chigwell-marquees.jpg","small-civil-ceremony-venue-luxury-marquee-event-hire-essex-the-chigwell-marquees.jpg","engagement-venue-hire-luxury-marquee-hire-essex-the-chigwell-marquees.jpg","indian-weddings-asian-weddings-essex-the-chigwell-marquees.jpg","wedding-venue-chigwell-essex-1.jpg","party-venues-near-me-Essex.jpg","asian-wedding-venue-near-me-essex-london.jpg","civil-ceremonies-essex.jpg","wedding-venue-essex.jpg","party-venues-near-me.jpg","essex-party-marquees.jpg","chigwell-marquees-about-us-1.png","beautiful-essex-wedding-venue.jpg","asian-wedding-mandap-hire-1.jpg","marquee-hire-chigwell.jpg","party-venue-chigwell.jpg","engagement-parties-in-essex-the-chigwell-marquees.jpg","engagement-venues-to-hire-essex-the-chigwell-marquee.jpg","engagement-parties-in-essex.jpg","engagement-party-venues.jpg","asian-wedding-mandap-hire.jpg","chigwell-marquees-civil-ceremonies-02.jpg","chigwell-marquees-civil-ceremonies-01.jpg","chigwell-marquees-wedding-events-06.jpg","chigwell-marquees-wedding-events-05.jpg","chigwell-marquees-wedding-events-04.jpg","chigwell-marquees-wedding-events-03.jpg","chigwell-marquees-wedding-events-02.jpg","chigwell-marquees-wedding-events-01.jpg","chigwell-marquees-themed-events-05.jpg","chigwell-marquees-themed-events-04.jpg","chigwell-marquees-themed-events-03.jpg","chigwell-marquees-themed-events-02.jpg","chigwell-marquees-themed-events-01.jpg","chigwell-marquees-corporate-events-05.jpg","chigwell-marquees-corporate-events-04.jpg","chigwell-marquees-corporate-events-03.jpg","chigwell-marquees-corporate-events-02.jpg","chigwell-marquees-corporate-events-01.jpg","christening-venues-near-me-essex-chigwell-marquees.jpg","christmas-party-venue-essex-chigwell-marquees.jpg","corporate-event-venue-hire-essex-chigwell-marquees.jpg","large-corporate-venue-hire-essex-chigwell-marquees.jpg","civil-ceremony-venue-in-essex-civil-ceremony-marquee-hire-essex-the-chigwell-marquees.jpg","birthday-party-venue-in-essex-childrens-party-venues-essex-the-chigwell-marquees.jpg","birthday-party-venue-in-essex-childrens-birthday-venues-essex-the-chigwell-marquees.jpg","party-venue-in-essex-marquee-hire-essex-essex-the-chigwell-marquees.jpg","bengali-weddings-bengali-marquee-wedding-venues-essex-the-chigwell-marquees.jpg","asian-weddings-asian-marquee-wedding-venues-essex-the-chigwell-marquees.jpg","birthday-party-venue-party-marquee-essex-the-chigwell-marquees.jpg","civil-ceremony-venue-near-me-marquee-event-hire-essex-the-chigwell-marquees.jpg","civil-ceremony-marquee-hire-marquee-event-hire-essex-the-chigwell-marquees.jpg","civil-ceremony-venue-hire-marquee-event-hire-essex-the-chigwell-marquees.jpg","bengali-weddings-wedding-venues-essex-the-chigwell-marquees.jpg","asian-weddings-wedding-venues-essex-the-chigwell-marquees.jpg","wedding-venue-hire-luxury-wedding-marquees-essex-the-chigwell-marquees.jpg","asian-wedding-venue-luxury-wedding-marque-essex-the-chigwell-marquees.jpg","wedding-venue-hire-marquee-wedding-venues-essex-the-chigwell-marquees.jpg","bengali-weddings-pakistani-wedding-essex-the-chigwell-marquees.jpg","asian-weddings-indian-weddings-essex-the-chigwell-marquees.jpg","party-venue-hire-birthday-party-venue-essex-the-chigwell-marquees.jpg","party-venues-essex-private-party-venue-essex-the-chigwell-marquees.jpg","party-venues-essex-party-venues-hire-essex-the-chigwell-marquees.jpg","party-venues-hire-party-venues-essex-essex-the-chigwell-marquees.jpg","civil-ceremoney-venue-hire-essex-the-chigwell-marquees.jpg","civil-ceremoney-venue-to-rent-essex-the-chigwell-marquees.jpg","asian-weddings-essex-the-chigwell-marquees.jpg","civil-ceremonies-essex-chigwell-marquees.jpg","wedding-venue-essex-chigwell-marquees.jpg","party-venue-essex-chigwell-marquees.jpg","birthday-party-venue-essex-chigwell-marquees.jpg","xmas-bookings-2019.jpg","the-chigwell-marquees-open-day.jpg","party-venue-essex.jpg","wedding-venue-essex-1.jpg","garden-wedding-essex-london-chigwell-marquees.jpg","mega-marquee-wedding-venue-essex-london-chigwell-marquees.jpg","mini-marquee-party-venue-essex-london-chigwell-marquees.jpg"];
